#!/bin/bash
#
#  This file is the first thing that is executed when Securizant is 
#  booted.
#  It will first try to located a SYSTEM partition, then
#
#
#
export PATH=/bin:/sbin:/mounts/ROOT/bin:/mounts/ROOT/sbin

main()
{
	mount_proc
	mount_os_partition
	mount_root_image
	pivot_roots
	leave_linuxrc
}

#
#  First must mount proc so that we can use e2fs labels
mount_proc()
{
	mount -n -s proc -t proc /mounts/PROC
	if [ $? -eq 0 ]
	then
		PROC_MOUNTED=true
	fi
}

#
#  Attempt to mount the OS partition.
#  Try to mount CDROM first if there is a CD
#  in the drive, else mount SYSTEM partition.
#
mount_os_partition()
{
	mount_cdrom
	if [ -z $ISO_MOUNTED ]
	then
		mount_system
	fi
}

#
#  Mounts the CD-ROM, if not CD-ROM or not securizant media fails, else sets
#  ISO_MOUNTED to true. 
#
mount_cdrom()
{
	mount -n -s /dev/cdroms/cdrom0 /mounts/ISO -o ro
	if [ $? -eq 0 ]
	then
		ISO_MOUNTED=CDROM0
	else
		mount -n -s /dev/cdroms/cdrom1 /mounts/ISO -o ro
		if [ $? -eq 0 ]
		then
			ISO_MOUNTED=CDROM1
		fi
	fi

	if [ ! -f /mounts/ISO/isolinux ]
	then
		ISO_MOUNTED = ""
		/bin/umount /mounts/ISO
	fi
}

mount_system()
{
	mount -n -s -L SYSTEM /mounts/SYSTEM -o ro
	if [ $? -eq 0 ]
	then
		SYSTEM_MOUNTED=true
	fi
}

mount_root_image()
{
	if [ -d /mounts/ISO/operating_system/media_images ]
	then
		mount -n -s /mounts/ISO/operating_system/media_images/root.e2 /mounts/ROOT -o loop,ro

	elif [ -d /mounts/SYSTEM/operating_system/media_images ]
	then
	        mount -n -s /mounts/SYSTEM/operating_system/media_images/root.e2 /mounts/ROOT  -o loop,ro
	else
		echo "!!!! Could not find ROOT image!!!!!"
		bash
	fi
}

pivot_roots()
{
	echo Pivoting roots
	#bash

	#
	#  Pivot root
	#
	cd /mounts/ROOT
	pivot_root . ./mounts/INITRD

	#
	#  Move mounted partitions
	#

	if [ "$PROC_MOUNTED" = "true" ]
	then
		mount -n --move /mounts/INITRD/mounts/PROC /mounts/PROC
	fi
	if [ "$SYSTEM_MOUNTED" = "true" ]
	then
		mount -n --move /mounts/INITRD/mounts/SYSTEM /mounts/SYSTEM
	fi
	if [ -n $ISO_MOUNTED ]
	then
		mount -n --move /mounts/INITRD/mounts/ISO /mounts/ISO
	fi
	mount -n --move /mounts/INITRD/dev /dev
}

leave_linuxrc()
{
	echo Leaving linuxrc
	exec chroot . /sbin/init <dev/console >dev/console 2>&1
}

main $@
